### ISSUE TITLE
Store configuration in home dotfile

### ISSUE THREAD

**Issue by ErikBoesen** [kiwiz/keep-cli#4]
This is something that would be especially useful to implement. If users want to be able to run `keep` as a command from any working directory, or to store their configuration in a dotfiles repository, they'd have a much easier time if the configuration for this tool were in a constant location in the filesystem rather than just in whichever directory they cloned `keep-cli` to.

**Comment by kiwiz** [comment]
Implemented in c0fb9837641c7bb1505d44e874b102b3d1b23116.
